### PR TITLE
Add quickfix for csso parse error

### PR DESCRIPTION
**Pull request by jhnns**
This pull request adds a quickfix for the csso parse error.

#36
https://github.com/css/csso/issues/185

### CODE REVIEW

**Comment by sokra** [comment]
The test doesn't fail without the fix...

It doesn't seem to test the bug... Not sure... Maybe I do something wrong..

**Comment by jhnns** [comment]
Strange... the tests are failing as expected if I just return the content without modifying it

**Comment by jhnns** [comment]
bildschirmfoto 2015-02-03 um 23 30 35
bildschirmfoto 2015-02-03 um 23 30 59
bildschirmfoto 2015-02-03 um 23 31 46

**Comment by sokra** [comment]
> Strange... the tests are failing as expected if I just return the content without modifying it

Only because the atrifical `a{}` is missing...

Construct a test case that demonstrate the bug...

**Comment by jhnns** [comment]
See my first picture. When the content is returned without adding the `a{}`, the tests are failling.

**Comment by benurb** [comment]
I have the same problem and the PR fixed it for me. Thanks :+1:

**Comment by navinpeiris** [comment]
:+1:

**Comment by sokra** [comment]
I would like to reprodude it before merging... So please give me a testcase.

**Comment by benurb** [comment]
I've found the underlying problem in my input files. They were generated by the sass preprocessor, which adds a byte-order-mark to the beginning of the resulting CSS file. csso was unable to parse this file correctly so I opened a PR there: css/csso/pull/223
@sokra: Maybe the BOM-removal-logic is something you want to add to your css-loader, too. But this quickfix here in this PR is not needed imho.

**Comment by svnlto** [comment]
:+1:

**Comment by sokra** [comment]
> @sokra: Maybe the BOM-removal-logic is something you want to add to your css-loader, too. But this quickfix here in this PR is not needed imho.

Maybe we can add this to webpack...

**Comment by sokra** [comment]
> @sokra: Maybe the BOM-removal-logic is something you want to add to your css-loader, too. But this quickfix here in this PR is not needed imho.
> Maybe we can add this to webpack...

We already have this: https://github.com/webpack/core/blob/master/lib/NormalModuleMixin.js#L15-L22

**Comment by sokra** [comment]
Closing as we are no longer using csso...

**Pull request closed without merging**
