### PR TITLE
expose getLocalIdent

### LINKED ISSUE #292: Custom localIdent name as a function
Right now `localIdentName` allows me to put in a certain pattern `[name]_[hash]` for PostCSS I have a custom `generateScopedName` function that basically spit out a custom shorter name based on all my classes (kinda like module ids). Something similar to:

``` js
function generateScopedName (...args) {
    const longName = exports.generateLongName(...args)
    if (WEBPACK_CSS_NAME_MAP[longName] === undefined) {
        WEBPACK_CSS_NAME_MAP[longName] = `${PREFIX}${Object.keys(WEBPACK_CSS_NAME_MAP).length}`
    }

    return WEBPACK_CSS_NAME_MAP[longName]
}
```

However, with this plugin I can't pass `generateScopedName` as a function like PostCSS. Any suggestions?

### PR DESCRIPTION
**Pull request by longlho**
fixes #292

### CODE REVIEW

**Comment by sokra** [comment]
Without the module loading stuff it sounds doable. Just pass getLocalId via option/query. webpack 2 accepts non-JSON options.

**Comment by MrCheater** [comment]
Add an example of usage to documentation, please.

**Comment by longlho** [comment]
@sokra gotcha I'll remove that

**Comment by longlho** [comment]
@sokra @MrCheater done

**Comment by longlho** [comment]
can we merge & release :)?

**Comment by esquevin** [comment]
Any idea when this will be released ?

**Comment by bebraw** [comment]
@esquevin Looks like it's included in `0.26.1` released three days ago.

**Pull request merged**
