### PR TITLE
Resolving grammatical issue in README.md file

### PR DESCRIPTION
**Pull request by mrsteele**
Just spotted this light grammatical error and thought I would resolve it.

Ended up changing the whole sentence as it didn't seem quite right, but please let me know if you think it is worse by... well... denying the pull 😉

### CODE REVIEW

**Comment by bebraw** [comment]
Looks good to me. 👍

**Comment by mrsteele** [comment]
@bebraw Would you mind merging this in please?

**Comment by bebraw** [comment]
I think the maintainers will get onto it eventually. 👍

**Comment by sokra** [comment]
Thanks

**Pull request merged**
