### PR TITLE
Allow Closure Compiler name mangling.

### PR DESCRIPTION
**Pull request by quadrupleslap**

### CODE REVIEW

**Comment by sokra** [comment]
This require test cases. Also try difficult stuff i. e. selectors starting with numbers or dashes.

``` css
.\5-x { }
.\- { }
```

**Comment by quadrupleslap** [comment]
Uh, sorry for the necropost, I have no clue how to write tests for this.

According to http://timelessrepo.com/json-isnt-a-javascript-subset however, there are only two characters for which JSON won't evaluate in a Javascript interpreter, and both are separators, so I think it should be fine.

**Comment by quadrupleslap** [comment]
Bump?

**Comment by d3viant0ne** [comment]
As @sokra said, this PR isn't going to land without test cases to cover the changes.

**Pull request closed without merging**
