### PR TITLE
Update cssnano options. Fixes #126.

### LINKED ISSUE #126: cssnano deprecated options
I'm currently using `css-loader` (@0.16.0) and `style`-loader (@0.12.3) with the UglifyJsPlugin and I'm getting the following warnings:

```
The unused option is deprecated. Please use options.discardUnused instead.
The urls option is deprecated. Please use options.normalizeUrl instead.
The idents option is deprecated. Please use options.mergeIdents instead.
The idents option is deprecated. Please use options.reduceIdents instead.
```

Seems that cssnano changed some of its options.

### PR DESCRIPTION
**Pull request by ben-eb**

### CODE REVIEW

**Comment by wouter-willems** [comment]
:+1:

**Comment by p0wl** [comment]
:+1:

**Comment by timse** [comment]
:100:

**Comment by sokra** [comment]
Thanks

**Comment by ben-eb** [comment]
Cheers! :beers:

**Pull request merged**
