### PR TITLE
Add `files` to `package.json`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
I'd rather have a whitelist with the `files` field, like we do in most of the webpack packages.

**Comment by wtgtybhertgeghgtwtg** [comment]
I just used the `.npmignore` since it was there.  I will update the PR to use `files`.

**Comment by wtgtybhertgeghgtwtg** [comment]
Now usings `files` in `package.json`.

**Comment by SpaceK33z** [comment]
Thanks!

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for merging.

**Pull request merged**
