### PR TITLE
Use lodash.clone to copy query-params for CleanCSS

### PR DESCRIPTION
**Pull request by SimenB**
As discussed on Gitter https://gitter.im/webpack/webpack?at=556d9496463d0c7c066db585

### CODE REVIEW

**Comment by SimenB** [comment]
@sokra Any thoughts on this? I'd prefer not having to float a patch until a better solution is found (unless it's tomorrow). :smile:

**Comment by sokra** [comment]
closing because using postcss now.

**Comment by SimenB** [comment]
@sokra Could you update the readme? It still points to CleanCSS
https://github.com/webpack/css-loader/blob/master/README.md#minification

**Comment by SimenB** [comment]
@sokra How do I pass options to `cssnano`? I'd like to pass `false` to `autoprefixer`
http://cssnano.co/options/

**Comment by sokra** [comment]
yes, you can do that now with 0.16.0, `css-loader?-autoprefixer`

**Comment by SimenB** [comment]
Awesome, thanks!

**Pull request closed without merging**
