### PR TITLE
Make sure 'map' is defined

### LINKED ISSUE #84: css-loader doesn't work anymore with v0.15.1
after updated to v0.15.1 from v0.14.x, css loader doesn't work any more.
error1

here is the config:

```js
const sassLoaders = [
  "css",
  "sass?" + ["outputStyle=expanded",
    "includePaths[]=" + nodeModulesPath,
    "includePaths[]=" + bowerComponentsPath].join("&")
].join("!");
```
later on
```js
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract("style-loader", sassLoaders, {
          publicPath: './'
        })

      },
```

### PR DESCRIPTION
**Pull request by stevewillard**
Fixes #84

### CODE REVIEW

**Comment by rbartoli** [comment]
I've tested this fix and it works. Is it possible to merge it please?

**Comment by markdalgleish** [comment]
This fixes the issue, but drops the test coverage. @sokra any thoughts on how we should test the treatment of source maps?

**Comment by markdalgleish** [comment]
Thanks for the original PR, but I needed to add tests for this for the coverage check to pass.

This issue should now be fixed in v0.15.3.

**Comment by moretti** [comment]
@markdalgleish 
I've just updated to 1.5.3 (from 1.4.5) and I still have the same issue:

```
ERROR in ./~/css-loader?module&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/app/App.css
Module build failed: Error: "myApp/App.css" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (myApp/node_modules/css-loader/node_modules/postcss/node_modules/source-map/lib/source-map/source-map-consumer.js:677:15)
    at Input.origin (myApp/node_modules/css-loader/node_modules/postcss/lib/input.js:91:31)
    at Input.error (myApp/node_modules/css-loader/node_modules/postcss/lib/input.js:61:27)
    at Rule.error (myApp/node_modules/css-loader/node_modules/postcss/lib/node.js:68:38)
    at myApp/node_modules/css-loader/node_modules/postcss-modules-local-by-default/index.js:240:20
    at myApp/node_modules/css-loader/node_modules/postcss/lib/container.js:141:30
    at myApp/node_modules/css-loader/node_modules/postcss/lib/container.js:102:26
    at Root.each (myApp/node_modules/css-loader/node_modules/postcss/lib/container.js:89:22)
    at Root.eachInside (myApp/node_modules/css-loader/node_modules/postcss/lib/container.js:101:21)
    at Root.eachRule (myApp/node_modules/css-loader/node_modules/postcss/lib/container.js:139:21)
 @ ./src/app/App.css 4:14-178 13:2-17:4 14:20-184
```

Here's my  `webpack.config` configuration:

```.js
// ...
module: {
  loaders: [
     { test: /\.css$/, loaders: ['style', 'css?module&localIdentName=[name]__[local]___[hash:base64:5]', 'postcss'] },
     // ...
  ],
},
postcss: [
  require('postcss-import'),
  require('postcss-custom-properties')(),
  require('postcss-calc'),
  require('postcss-color-function')(),
  require('postcss-media-minmax')(),
  require('postcss-custom-media')(),
  require('autoprefixer-core'),
],
// ...
```

**Comment by markdalgleish** [comment]
@moretti This looks like a different error. Could you open a new issue?

**Pull request closed without merging**
