### PR TITLE
Fixes issue #133 with unicode strings

### PR DESCRIPTION
**Pull request by tadjohnston**
https://github.com/webpack/css-loader/issues/133

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@sokra this looks good but I wonder if maybe these tests should be updated to reflect the same node versions as webpack/webpack. We can get back around to it if we need to, I'll assign to me to keep track.

**Comment by sokra** [comment]
Thanks

@TheLarkInn yep

**Comment by MicheleBertoli** [comment]
@sokra it would be awesome to get this on `npm`, thanks! :)

**Comment by ricsv** [comment]
+1 on `npm`, would be really great!

**Pull request merged**
